# Generated by Django 4.1.2 on 2022-10-25 23:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0004_alter_chat_room_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='message',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='chat',
            name='room_name',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='chats.room'),
        ),
    ]
