# Generated by Django 4.1.2 on 2022-10-26 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0005_alter_chat_message_alter_chat_room_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='room_name',
            new_name='roomname',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='room_name',
            new_name='roomname',
        ),
    ]
