# Generated by Django 4.1.2 on 2022-10-28 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0006_rename_room_name_chat_roomname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='roomname',
            new_name='roomn',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='roomname',
        ),
        migrations.AddField(
            model_name='chat',
            name='room',
            field=models.ForeignKey(blank=True, default=2, on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='chats.room'),
            preserve_default=False,
        ),
    ]
